### ISSUE TITLE
Make this available on homebrew

### ISSUE THREAD

**Issue by ryboe** [develerik/git-credential-1password#11]
### Is your feature request related to a problem? Please describe.

I want to easily install `git-credential-1password` with `brew`. I don't want to build it from source.

### Describe the solution you'd like

I'd like to install `git-credential-1password` by typing this:

```sh
brew install git-credential-1password
```

### Describe alternatives you've considered

Alternative: Don't publish the install formula in the official

```sh
brew tap develerik/git-credential-1password
brew install develerik/git-credential-1password
```

This is a little more work for the user, but doesn't require you to get the formula merged into [`homebrew/core`](https://github.com/Homebrew/homebrew-core).

**Comment by develerik** [comment]
I created the tap `develerik/tools` (https://github.com/develerik/homebrew-tools)
