### ISSUE TITLE
Seen as Trojan.Win64.Convagent.gen or Unsafe / Malicious 

### ISSUE THREAD

**Issue by MarcHagen** [develerik/git-credential-1password#13]
### Describe the vulnerability

Windows exe is detected as a virus: 

VHO:Trojan.Win64.Convagent.gen
https://www.virustotal.com/gui/file/b9b79fabb58981f1e2668a9af88090f0aa1ee716c64683c468caa8cd2880fd68

### Additional context

- OS: 
- OS Build:  
- Shell: 
- Helper Version: 
- Git Version: 
- 1Password CLI Version:

**Comment by develerik** [comment]
Hi,

I upgraded the go version and some libraries. I did a local release and tested again with VirusTotal.
It seems like the Trojan recognition is gone now: https://www.virustotal.com/gui/file/f0f1177340dc9ea40874d9648bc4e4d8ac824567b60203270811574212ef8b02

This fix will be included in the next release.
