### ISSUE TITLE
open : no such file or directory

### ISSUE THREAD

**Issue by RubenVerborgh** [develerik/git-credential-1password#17]
### Describe the bug

I get the error `open : no such file or directoryUsername for 'https://mygitrepo.com':`

### To Reproduce

1. Follow the installation steps
2. Confirm that `git-credential-1password` is working
3. Type `git push`

### Expected behavior

My credentials from 1Password are loaded

### Additional context

```
Version: 1.2.0
Git Version: 2.37.3
1Password CLI Version: 2.7.1
Architecture: arm64
Operating System: darwin
```

**Comment by WizBangCrash** [comment]
I get the same error when trying to use the utility.

1Password CLI version: 2.12.0
git version: 2.39.0
macOS version: 13.1

Is there any more information I can provide to help get my issue resolved?

**Comment by develerik** [comment]
Hi, sorry for the late reply.

Apparently I forgot that fall through in a switch statement must be explicitly set in go. I'll include the fix in the next version (to be released in the next few days). In the meantime, you can build it from the `17-open-no-search-file-or-directory` branch if you want.
