### ISSUE TITLE
Let's include your project on 1Password's Community Spotlight

### ISSUE THREAD

**Issue by techcraver** [develerik/git-credential-1password#22]
Hey there. I'm a developer evangelist at 1Password. We've spied your project and would love to include it on our Developer Portal on the Dev [Community spotlight](https://developer.1password.com/community). 

Would you be up for submitting a [PR](https://github.com/1Password/developer-community-projects/pulls)?

**Comment by develerik** [comment]
This is a great idea :) I opened [add git-credential-1password](https://github.com/1Password/developer-community-projects/pull/12)

**Comment by develerik** [comment]
The PR was merged
